spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: quizapp

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
